### ISSUE TITLE
请问能否动态支持类或结构体变量的动态注册

### ISSUE THREAD

**Issue by luofengBJ** [AIGMix/AIGCJson#5]
感谢作者设计出了这么优秀的代码可以在c++中快速进行此类转换。
目前的设计是，在类定义中，先对要输出json的Key和Object值调用JSON_HELPER进行注册，
碰到了因为数据的问题，json的Object或者Key值和数量是动态变化的，没有办法在代码设计时就确定下来，结合代码是支持成员名称重命名的，感觉应该是可以做得了的，但是没有什么思路，不知道如何修改好。
请问作者对这种需求有没有思路呢，谢谢。

**Comment by yaronzz** [comment]
> 

现在类成员的注册都是在类中JSON_HELPER加的，所以不支持动态增加。不知道类外注册能不能动态增加，不过这个还没写。

**Comment by luofengBJ** [comment]
如果把原本JSON_HELPER的内容，修改为在类中进行重载，是否可以实现类似的功能呢？当然这只是我的初步想法，对这个代码还不是很熟悉，作者认为呢？这种方法是否可行

**Comment by yaronzz** [comment]
JSON_HELPER 里面的内容重载不了，需要用到宏定义的__VA_ARGS__来遍历类成员
```
#define AIGC_JSON_HELPER(...)                                                            \
    std::map<std::string, std::string> __aigcDefaultValues;                              \
    bool AIGCJsonToObject(aigc::JsonHelperPrivate &handle,                               \
                          rapidjson::Value &jsonValue,                                   \
                          std::vector<std::string> &names)                               \
    {                                                                                    \
        std::vector<std::string> standardNames = handle.GetMembersNames(#__VA_ARGS__);   \
        if (names.size() <= standardNames.size())                                        \
        {                                                                                \
            for (int i = names.size(); i < (int)standardNames.size(); i++)               \
                names.push_back(standardNames[i]);                                       \
        }                                                                                \
        return handle.SetMembers(names, 0, jsonValue, __aigcDefaultValues, __VA_ARGS__); \
    }                                                                                    \
```

**Comment by yaronzz** [comment]
回头想了一下，你这个为什么要动态增加？结构体不是本来就设计好的吗，还是动态给结构体增加一个变量？

**Comment by luofengBJ** [comment]
你好，我这边刚好碰到实际的业务是：
Json的Object的名字是不定的，数量也是不定的，但是这个Json的Object里面的结构是固定的，
他是把一个表加上不同的条件得到不同的结果，然后放在一个一个Object中，所以才需要动态注册名称
。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AIGMix/AIGCJson"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 下午2:13
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [AIGMix/AIGCJson] 请问能否动态支持类或结构体变量的动态注册 (Issue #5)





 
回头想了一下，你这个为什么要动态增加？结构体不是本来就设计好的吗，还是动态给结构体增加一个变量？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yaronzz** [comment]
这样的话，直接把json的Object名称改成结构体的变量名应该更好一点吧

**Comment by luofengBJ** [comment]
蒽~不是，因为Object的名称和数量，没有办法在代码编译阶段确定，所有没有办法提前写好变量进行注册，
所以我才在想能否进行动态注册，即现在的Json_Helper宏定义，是在代码运行阶段执行的，而不是编译阶段执行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AIGMix/AIGCJson"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 下午3:40
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [AIGMix/AIGCJson] 请问能否动态支持类或结构体变量的动态注册 (Issue #5)





 
这样的话，直接把json的Object名称改成结构体的变量名应该更好一点吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yaronzz** [comment]
比如：
```
struct peoples
{
	student A;
	student B;
}
```
而object的名称是C，那你将C改成A就行了。
还是说你想动态注册 Json_Helper(C) ?  可是结构体里的变量是写死的，不可能变成：
```
struct peoples
{
	student A;
	student B;
        student C;
}
```

**Comment by luofengBJ** [comment]
不是，People结构体是固定的，
但是我需要生成n个People，具体多少个也不知道，而且n个People的ObjectName也不是固定的。
例如：
People结构体固定的，但是json的A、B、C，名称和数量不是固定的







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AIGMix/AIGCJson"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 下午4:06
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [AIGMix/AIGCJson] 请问能否动态支持类或结构体变量的动态注册 (Issue #5)





 
比如：
 struct peoples { 	student A; 	student B; }  
而object的名称是C，那你将C改成A就行了。
 还是说你想动态注册 Json_Helper(C) ?  可是结构体里的变量是写死的，不可能变成：
 struct peoples { 	student A; 	student B;         student C; }  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by luofengBJ** [comment]
该问题可以删除吗？
