### ISSUE TITLE
版本测试问题

### ISSUE THREAD

**Issue by LostRaccoon** [AIGMix/AIGCJson#6]
我使用vs2015和vs2017编译运行调试，发现test.cpp中的my未能正确赋值，切换为vs2019或者mingw都可以正常显示，想了解下怎么更改可以支持这些版本，因为有些项目还在使用vs2015.

**Comment by yaronzz** [comment]
看看是不是没用c++11的问题

**Comment by LostRaccoon** [comment]
您好，c++11是有的，我在将提供的测试文件中将中文改为英文vs2017就可以正常出现了。我把string转换为utf8就好了，应该是低版本中文的string必须转换为utf8的格式。，
