### ISSUE TITLE
关于STL容器存储对象的序列化问题

### ISSUE THREAD

**Issue by majiaoliya** [AIGMix/AIGCJson#7]
如图所示，是否可以将
json 
```
   [
                    {"x": 77, "y": 4.14159, "name": "张飞1" },
                    {"x": 77, "y": 4.14159, "name": "张飞2" }
   ]
```
转化为std::list\<Stu\>对象呢

![image](https://user-images.githubusercontent.com/35868195/184300753-5c478525-9950-407c-94db-1594cee0c010.png)

**Comment by yaronzz** [comment]
可以参考这个例子：https://github.com/AIGMix/AIGCJson/blob/master/test/4nested.cpp

**Comment by majiaoliya** [comment]
> 可以参考这个例子：https://github.com/AIGMix/AIGCJson/blob/master/test/4nested.cpp

谢谢大佬  已解决
我仔细对比了4nested.cpp和后发现是忘记加public导致的编译报错
